name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_storage: ^11.7.2

  connectivity_plus: ^6.0.3
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.0

  
  
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  capitalize: ^0.0.2

  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.1.6
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
  
  
  
  
  
  
  
  
  
  
  
  
  