// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0vExzcWQOx71xjzxUerPrOxCnVgiA08',
    appId: '1:792821794386:android:ac31628e3a1a55837d018b',
    messagingSenderId: '792821794386',
    projectId: 'ecommerceapp-cc0ae',
    storageBucket: 'ecommerceapp-cc0ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3q3jpu7d-dxKg6kR3SwWFF9YP1IN5z2s',
    appId: '1:792821794386:ios:a3a3909810da4cfa7d018b',
    messagingSenderId: '792821794386',
    projectId: 'ecommerceapp-cc0ae',
    storageBucket: 'ecommerceapp-cc0ae.appspot.com',
    androidClientId: '792821794386-iu7hd6rn3gslako5kgvqo40nrnfjkd3c.apps.googleusercontent.com',
    iosClientId: '792821794386-fcfg9ng1chlnnbi8buhfr9csovoopgo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn9GgLHS-923D0hlZE5AZ69nQAhyRoHms',
    appId: '1:792821794386:web:f29d46176228e9d57d018b',
    messagingSenderId: '792821794386',
    projectId: 'ecommerceapp-cc0ae',
    authDomain: 'ecommerceapp-cc0ae.firebaseapp.com',
    storageBucket: 'ecommerceapp-cc0ae.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn9GgLHS-923D0hlZE5AZ69nQAhyRoHms',
    appId: '1:792821794386:web:f29d46176228e9d57d018b',
    messagingSenderId: '792821794386',
    projectId: 'ecommerceapp-cc0ae',
    authDomain: 'ecommerceapp-cc0ae.firebaseapp.com',
    storageBucket: 'ecommerceapp-cc0ae.appspot.com',
  );

}